"""
Comprehensive tests for the /extract endpoint.

Tests PDF extraction functionality including:
- Basic extraction with sample PDF
- Element ID generation
- Batch processing parameters
- Error handling
"""

import io
import json
from pathlib import Path
from fastapi.testclient import TestClient
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

from main import app

client = TestClient(app)


def create_test_pdf(num_pages: int = 2) -> bytes:
    """Create a simple test PDF with specified number of pages."""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    for page_num in range(1, num_pages + 1):
        c.drawString(100, 700, f"Test PDF - Page {page_num}")
        c.drawString(100, 650, f"This is a test document for extraction.")
        c.drawString(100, 600, f"It contains some sample text on page {page_num}.")
        c.showPage()
    
    c.save()
    buffer.seek(0)
    return buffer.read()


def test_extract_basic():
    """Test basic PDF extraction functionality."""
    # Create a simple test PDF
    pdf_content = create_test_pdf(num_pages=2)
    
    files = {"file": ("test.pdf", pdf_content, "application/pdf")}
    resp = client.post("/extract", files=files)
    
    assert resp.status_code == 200
    result = resp.json()
    
    # Verify response structure
    assert "markdown_content" in result
    assert "json_content" in result
    assert "metadata" in result
    
    # Check that content was extracted
    assert len(result["markdown_content"]) > 0
    assert "Test PDF" in result["markdown_content"]
    
    # Verify Azure DI structure
    analysis = result["json_content"]
    assert "content" in analysis
    assert "paragraphs" in analysis
    
    # Verify metadata
    metadata = result["metadata"]
    assert metadata["processing_type"] == "azure_di"
    assert "page_count" in metadata
    assert "processing_time" in metadata
    assert "file_size" in metadata
    assert "filename" in metadata
    assert metadata["element_ids_included"] is True  # default
    

def test_extract_with_element_ids():
    """Test that element IDs are generated by default."""
    pdf_content = create_test_pdf(num_pages=1)
    
    files = {"file": ("test.pdf", pdf_content, "application/pdf")}
    resp = client.post("/extract", files=files)
    
    assert resp.status_code == 200
    result = resp.json()
    
    # Check that paragraphs have IDs
    paragraphs = result["json_content"].get("paragraphs", [])
    if paragraphs:
        assert all("_id" in p for p in paragraphs)
        # Verify ID format
        first_id = paragraphs[0]["_id"]
        assert first_id.startswith("para_")
        assert len(first_id.split("_")) == 4  # type_page_index_hash
    

def test_extract_without_element_ids():
    """Test extraction with element IDs disabled."""
    pdf_content = create_test_pdf(num_pages=1)
    
    files = {"file": ("test.pdf", pdf_content, "application/pdf")}
    data = {"include_element_ids": "false"}
    resp = client.post("/extract", files=files, data=data)
    
    assert resp.status_code == 200
    result = resp.json()
    
    # Check that paragraphs don't have IDs
    paragraphs = result["json_content"].get("paragraphs", [])
    if paragraphs:
        assert all("_id" not in p for p in paragraphs)
    
    # Check metadata shows IDs were not included
    assert result["metadata"]["element_ids_included"] is False


def test_extract_return_both():
    """Test extraction returning both ID and non-ID versions."""
    pdf_content = create_test_pdf(num_pages=1)
    
    files = {"file": ("test.pdf", pdf_content, "application/pdf")}
    data = {"return_both": "true"}
    resp = client.post("/extract", files=files, data=data)
    
    assert resp.status_code == 200
    result = resp.json()
    
    # Should have both versions
    assert "json_content" in result
    assert "json_content_original" in result
    
    # ID version should have IDs
    paragraphs_with_ids = result["json_content"].get("paragraphs", [])
    if paragraphs_with_ids:
        assert all("_id" in p for p in paragraphs_with_ids)
    
    # Original version should not have IDs
    paragraphs_original = result["json_content_original"].get("paragraphs", [])
    if paragraphs_original:
        assert all("_id" not in p for p in paragraphs_original)


def test_extract_custom_batch_size():
    """Test extraction with custom batch size."""
    pdf_content = create_test_pdf(num_pages=3)
    
    files = {"file": ("test.pdf", pdf_content, "application/pdf")}
    data = {"batch_size": "1"}  # Process one page at a time
    resp = client.post("/extract", files=files, data=data)
    
    assert resp.status_code == 200
    result = resp.json()
    assert "json_content" in result
    assert result["metadata"]["batch_size"] == 1


def test_extract_invalid_file_type():
    """Test extraction with non-PDF file."""
    files = {"file": ("test.txt", b"This is not a PDF", "text/plain")}
    resp = client.post("/extract", files=files)
    
    # Should return an error (actual status depends on implementation)
    assert resp.status_code in [400, 422, 500]


def test_extract_empty_pdf():
    """Test extraction with empty PDF."""
    # Create an empty PDF
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    c.save()
    buffer.seek(0)
    
    files = {"file": ("empty.pdf", buffer.read(), "application/pdf")}
    resp = client.post("/extract", files=files)
    
    # Should still succeed but with minimal content
    assert resp.status_code == 200
    result = resp.json()
    assert "json_content" in result
    assert "metadata" in result


def test_extract_real_sample_pdf():
    """Test extraction with the real sample PDF if it exists."""
    # Skip this test if running in CI or without Azure credentials
    import os
    if not os.environ.get("AZURE_DI_KEY"):
        import pytest
        pytest.skip("Skipping Azure DI test - no credentials")
    
    sample_pdf_path = Path(__file__).parent / "sample_pdfs" / "05dracula.pdf"
    
    if sample_pdf_path.exists():
        with open(sample_pdf_path, "rb") as f:
            pdf_content = f.read()
        
        # Only process first 5 pages to keep test fast
        files = {"file": ("dracula_sample.pdf", pdf_content, "application/pdf")}
        data = {"batch_size": "5"}
        resp = client.post("/extract", files=files, data=data)
        
        assert resp.status_code == 200
        result = resp.json()
        
        # Should have substantial content
        assert len(result["markdown_content"]) > 1000
        assert "json_content" in result
        assert "metadata" in result
        
        # Check for proper extraction
        assert "Dracula" in result["markdown_content"] or "DRACULA" in result["markdown_content"]


def test_extract_with_segmentation_basic():
    """Test extraction with segmentation enabled."""
    # Create a multi-page PDF with enough content for segmentation
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    # Page 1 - Introduction
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 700, "Introduction")
    c.setFont("Helvetica", 12)
    for i in range(20):
        c.drawString(100, 650 - i*20, f"This is paragraph {i+1} of the introduction section.")
    c.showPage()
    
    # Page 2 - Chapter 1
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 700, "Chapter 1: Overview")
    c.setFont("Helvetica", 12)
    for i in range(20):
        c.drawString(100, 650 - i*20, f"This is paragraph {i+1} of chapter 1.")
    c.showPage()
    
    # Page 3 - Chapter 2
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 700, "Chapter 2: Details")
    c.setFont("Helvetica", 12)
    for i in range(20):
        c.drawString(100, 650 - i*20, f"This is paragraph {i+1} of chapter 2.")
    c.showPage()
    
    c.save()
    buffer.seek(0)
    
    files = {"file": ("test_segmentation.pdf", buffer.read(), "application/pdf")}
    data = {
        "enable_segmentation": "true",
        "segment_min_tokens": "100",
        "segment_max_tokens": "1000"
    }
    
    resp = client.post("/extract", files=files, data=data)
    assert resp.status_code == 200
    result = resp.json()
    
    # Verify segmentation is present
    assert "segments" in result
    assert isinstance(result["segments"], list)
    assert len(result["segments"]) > 0
    
    # Verify segment structure
    first_segment = result["segments"][0]
    assert "segment_id" in first_segment
    assert "source_file" in first_segment
    assert "token_count" in first_segment
    assert "structural_context" in first_segment
    assert "elements" in first_segment
    
    # Verify metadata includes segmentation info
    metadata = result["metadata"]
    assert metadata["segmentation_enabled"] is True
    assert "segment_count" in metadata
    assert metadata["segment_count"] == len(result["segments"])
    assert "segment_config" in metadata
    assert metadata["segment_config"]["min_tokens"] == 100
    assert metadata["segment_config"]["max_tokens"] == 1000


def test_extract_segmentation_disabled():
    """Test that segmentation is disabled by default."""
    pdf_content = create_test_pdf(num_pages=2)
    
    files = {"file": ("test.pdf", pdf_content, "application/pdf")}
    # Don't specify enable_segmentation (defaults to False)
    resp = client.post("/extract", files=files)
    
    assert resp.status_code == 200
    result = resp.json()
    
    # Segments should not be present
    assert "segments" not in result
    assert result["metadata"]["segmentation_enabled"] is False


def test_extract_segmentation_token_limits():
    """Test that segmentation respects token limits."""
    # Create a PDF with varied content lengths
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    # Add multiple sections with different content lengths
    for i in range(5):
        c.setFont("Helvetica-Bold", 14)
        c.drawString(100, 700, f"Section {i+1}")
        c.setFont("Helvetica", 12)
        
        # Add varying amounts of content
        y_pos = 650
        for j in range(10 + i * 5):  # Increasing content per section
            text = f"Line {j+1}: This is sample text content for testing segmentation behavior. " * 3
            c.drawString(100, y_pos, text[:100])  # Truncate to fit on page
            y_pos -= 20
            if y_pos < 100:
                break
        c.showPage()
    
    c.save()
    buffer.seek(0)
    
    files = {"file": ("test_limits.pdf", buffer.read(), "application/pdf")}
    data = {
        "enable_segmentation": "true",
        "segment_min_tokens": "500",
        "segment_max_tokens": "2000"
    }
    
    resp = client.post("/extract", files=files, data=data)
    assert resp.status_code == 200
    result = resp.json()
    
    # Verify all segments respect token limits
    for segment in result["segments"]:
        assert segment["token_count"] <= 2000
        # Note: min_tokens is a soft limit, so very small documents might have smaller segments


def test_extract_segmentation_with_element_ids():
    """Test segmentation preserves element IDs."""
    pdf_content = create_test_pdf(num_pages=3)
    
    files = {"file": ("test.pdf", pdf_content, "application/pdf")}
    data = {
        "include_element_ids": "true",
        "enable_segmentation": "true",
        "segment_min_tokens": "50",
        "segment_max_tokens": "500"
    }
    
    resp = client.post("/extract", files=files, data=data)
    assert resp.status_code == 200
    result = resp.json()
    
    # Verify elements in segments have IDs
    assert "segments" in result
    for segment in result["segments"]:
        for element in segment["elements"]:
            # Element IDs should be present when include_element_ids is true
            if "content" in element:  # Only elements with content get IDs
                assert "_id" in element